/**
 * Generates LEGAL-REVIEW.md — a checklist of every state legal value grouped by
 * confidence, so the founder can review low/medium-confidence entries fast.
 *
 * Run:  npm run legal-audit
 * (Node strips the type-only imports, so no build step is needed.)
 */
import { writeFileSync } from "node:fs";
import { US_STATES } from "../src/lib/states.ts";
import { DEPOSIT_INTEREST } from "../src/tools/security-deposit-interest/data.ts";
import { RENT_INCREASE } from "../src/tools/rent-increase-notice/data.ts";
import { LATE_FEE } from "../src/tools/late-fee/data.ts";
import { DEPOSIT_RETURN } from "../src/tools/security-deposit-return/data.ts";

type Cited = { cite: { statute: string; confidence: string; lastVerified: string } };

const NAME = new Map(US_STATES.map((s) => [s.code, s.name]));

const datasets: Record<string, Record<string, Cited>> = {
  "Security deposit interest": DEPOSIT_INTEREST,
  "Rent increase notice": RENT_INCREASE,
  "Late fee": LATE_FEE,
  "Security deposit return": DEPOSIT_RETURN,
};

interface Row {
  tool: string;
  state: string;
  statute: string;
  confidence: string;
  lastVerified: string;
}

const rows: Row[] = [];
for (const [tool, map] of Object.entries(datasets)) {
  for (const [code, rule] of Object.entries(map)) {
    rows.push({
      tool,
      state: NAME.get(code) ?? code,
      statute: rule.cite.statute,
      confidence: rule.cite.confidence,
      lastVerified: rule.cite.lastVerified,
    });
  }
}

const counts = { high: 0, medium: 0, low: 0 } as Record<string, number>;
rows.forEach((r) => (counts[r.confidence] = (counts[r.confidence] ?? 0) + 1));

const section = (level: string) => {
  const list = rows
    .filter((r) => r.confidence === level)
    .sort((a, b) => a.tool.localeCompare(b.tool) || a.state.localeCompare(b.state));
  if (!list.length) return "";
  const lines = list.map(
    (r) => `- [ ] **${r.tool} — ${r.state}** · \`${r.statute}\` (verified ${r.lastVerified})`,
  );
  return `\n### ${level.toUpperCase()} confidence (${list.length})\n\n${lines.join("\n")}\n`;
};

const md = `# Legal data review checklist

> Auto-generated by \`npm run legal-audit\`. Re-run it after editing any
> \`src/tools/*/data.ts\` file. Work top-down: clear every **LOW**, then spot-check
> **MEDIUM**. Check the box once you've confirmed the value against the cited
> statute and updated \`lastVerified\`.

**Totals:** ${rows.length} state rules — ` +
  `${counts.low ?? 0} low · ${counts.medium ?? 0} medium · ${counts.high ?? 0} high.

Each tool's data lives in one file:
- \`src/tools/security-deposit-interest/data.ts\`
- \`src/tools/rent-increase-notice/data.ts\`
- \`src/tools/late-fee/data.ts\`
- \`src/tools/security-deposit-return/data.ts\`
${section("low")}${section("medium")}${section("high")}`;

writeFileSync(new URL("../LEGAL-REVIEW.md", import.meta.url), md);
console.log(
  `Wrote LEGAL-REVIEW.md — ${rows.length} rules (${counts.low ?? 0} low, ${counts.medium ?? 0} medium, ${counts.high ?? 0} high).`,
);
